//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.28 at 02:01:14 PM JST 
//


package jp.go.affrc.narc.metxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="nw_lat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="nw_lon" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="se_lat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="se_lon" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "area")
public class Area {

    @XmlAttribute(name = "nw_lat", required = true)
    protected double nwLat;
    @XmlAttribute(name = "nw_lon", required = true)
    protected double nwLon;
    @XmlAttribute(name = "se_lat", required = true)
    protected double seLat;
    @XmlAttribute(name = "se_lon", required = true)
    protected double seLon;

    /**
     * Gets the value of the nwLat property.
     * 
     */
    public double getNwLat() {
        return nwLat;
    }

    /**
     * Sets the value of the nwLat property.
     * 
     */
    public void setNwLat(double value) {
        this.nwLat = value;
    }

    /**
     * Gets the value of the nwLon property.
     * 
     */
    public double getNwLon() {
        return nwLon;
    }

    /**
     * Sets the value of the nwLon property.
     * 
     */
    public void setNwLon(double value) {
        this.nwLon = value;
    }

    /**
     * Gets the value of the seLat property.
     * 
     */
    public double getSeLat() {
        return seLat;
    }

    /**
     * Sets the value of the seLat property.
     * 
     */
    public void setSeLat(double value) {
        this.seLat = value;
    }

    /**
     * Gets the value of the seLon property.
     * 
     */
    public double getSeLon() {
        return seLon;
    }

    /**
     * Sets the value of the seLon property.
     * 
     */
    public void setSeLon(double value) {
        this.seLon = value;
    }

}
